check_interval = 60
# interval seconds(integer) for check battery level.

# ==================================================
# Optional fields below:

notification_method = "TauriWinrtToast"
# Optional field
# This field defines notification method (notifier crate).
# Options now: "TauriWinrtToast"(default), "WinrtToastReborn"

mode_names = [""]
# Optional field
# This field defines order of mode.
# Normally, the order of written in file is unsaved because of using hash.
# The mode not written in this field will be added to position later than modes written in this field.
# The mode not defined notifications will not be added to modes list.

initial_mode = ""
# Optional field
# This field defines mode (name of mode) to use initially.
# The default is modeless ("").

abort_on_error_except_change_mode = false
# Optional field
# This field defines whether to abort on error except change mode.
# Options: true, false(default)

notify_battery_during_change_mode = false
# Optional field
# This field defines whether to notify battery level during notify change mode.
# Options: true, false(default)

select_mode_when_starts = true
# Optional field
# This field defines whether to select mode when starts.
# Options: true(default), false

wait_seconds_after_select_mode_notify_when_starts = 10
# Optional field
# This field defines seconds to wait after select mode when starts.
# The default is 10 seconds.


# Optional fields end
# ==================================================

[[notifications]]
# "notifications" is optional, but each field of a notification setting is required.
# This fields define notifications that always notify.

percentage = "90+"
# express condition when notifications should be started.
# This consists of percentage(integer) and suffix "+" or "-".
# This example express that notifications will start whether battery level excess 90%
#
power_supply = "Adequate"
# express power supply status. This consists of "Adequate", "InAdequate", "None".

title = "Remove the plug!"
# notification title

message = "Your PC is now fully charged. Remove the plug"
# notification message

input_type = "SilentSpecifiedMinutes"
# Optional field
# This field defines type of input element of notification.
# Options: "ModeSelector"(default), "SilentSpecifiedMinutes"
# "TauriWinrtToast" method does not implement input element, so this field is not effective.

[[notifications]]
percentage = "45-"
power_supply = "None"
title = "Plug in!"
message = "The battery level of Your PC is low. Plug in."
